---
downloads: ~/.ansible-downloads/

configure_dotfiles: true
configure_terminal: true
configure_osx: false

# Set to 'true' to configure the Dock via dockutil.
configure_dock: true
dockitems_remove:
  - Launchpad
  - TV
  - Podcasts
  - 'App Store'
  - Mensajes
  - Mapas
  - FaceTime
  - Contactos
  - Fotos
  - Freeform
  - 'Música'
  - Descargas
  - Recordatorios

dockitems_persist:
 - name: "Focus To-Do"
   path: "/Applications/WebPomodoro.app/"
   pos: 3

configure_sudoers: false
sudoers_custom_config: ''
# Example:
# sudoers_custom_config: |
#   # Allow users in admin group to use sudo with no password.
#   %admin ALL=(ALL) NOPASSWD: ALL

dotfiles_repo: https://github.com/stratdes/dotfiles.git
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/Development/stratdes/dotfiles
dotfiles_files:
  - .zshrc
  - .gitignore
  - .inputrc
  - .osx
  - .vimrc

homebrew_installed_packages:
  - bash-completion
  - mcrypt
  - node
  - nvm
  - php
  - composer
  - symfony-cli
  - openssl
  - wget
  - zsh-history-substring-search
  - protobuf
  - rust

homebrew_taps:
  - buo/cask-upgrade
  - symfony-cli/tap

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - docker
  - firefox
  - google-chrome
  - sequel-ace
  - slack
  - 1password
  - appcleaner
  - mongodb-compass
  - phpstorm
  - postman
  - sketch
  - visual-studio-code
  - whatsapp
  - zoom
  - adguard
  - microsoft-office
  - balenaetcher

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps:
  - { id: 1258530160, name: "Focus To-Do" }

osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages:
  - laravel/installer
# - name: drush
#   state: present # present/absent, default: present
#   version: "^8.1" # default: N/A
gem_packages: []
# - name: bundler
#   state: present # present/absent/latest, default: present
#   version: "~> 1.15.1" # default: N/A
npm_packages:
  - name: "@angular/cli"
    state: present
# - name: webpack
#   state: present # present/absent/latest, default: present
#   version: "^2.6" # default: N/A
pip_packages: []
# - name: mkdocs
#   state: present # present/absent/latest, default: present
#   version: "0.16.3" # default: N/A

# Set to 'true' to configure Sublime Text.
configure_sublime: false
sublime_base_path: '~/Library/Application Support/Sublime Text'
sublime_config_path: "Packages/User"
sublime_package_control:
  - "DocBlockr"
  - "Dockerfile Syntax Highlighting"
  - "FileDiffs"
  - "GitHub Flavored Markdown Preview"
  - "Jinja2"
  - "Package Control"
  - "PHP-Twig"
  - "Pretty JSON"
  - "SublimeLinter"
  - "SublimeLinter-contrib-yamllint"
  - "TrailingSpaces"
  - "WordCount"

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
